Repository cpe-kmutt-student/comcamp34, pull requests merged in 2023-02, with the labels that each got.

#72 feat(registration-page-template)
  public/assets/regisPage/building.svg
  src/components/EmailInput.tsx
  src/components/GpaxInput.tsx
  src/components/Inputbox.tsx
  src/components/Telephoneinputbox.tsx
  src/components/registrationForm/ConsentForm.tsx
  src/pages/RegistrationPage.tsx
  tailwind.config.cjs
Labels: :sparkles: enhancement, frontend, form input, epic

#76 ✨feat: Step Form
  public/assets/svg/LeftArrow.svg
  public/assets/svg/RightArrow.svg
  src/components/registrationForm/ConsentForm.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, epic

#77 FIX : Styling file uploads data
  src/components/FileUploaderComponent.tsx
  src/components/registrationForm/UploadFilesForm.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, form input, epic

#80 No Responsive
  src/components/Checkboxinput.tsx
  src/components/GpaxInput.tsx
  src/components/Inputbox.tsx
  src/components/Textareainput.tsx.tsx
  src/components/registrationForm/DropdownData/course_name.json
  src/components/registrationForm/DropdownData/faculty_name.json
  src/components/registrationForm/DropdownData/grade_data.json
  src/components/registrationForm/DropdownData/study_plan_name.json
  src/components/registrationForm/DropdownData/university.json
  src/components/registrationForm/EducationForm.tsx
  src/components/registrationForm/InterestForm.tsx
Labels: :sparkles: enhancement, frontend, form input

#82 navbar sed leaw sus
  src/assets/nav-logo.png
  src/components/registrationForm/Navbar.tsx
Labels: :sparkles: enhancement, frontend

#81 Feat(condition section)
  package-lock.json
  package.json
  public/assets/frontPage/bgConditionsSection.png
  public/assets/frontPage/bgformobile.png
  public/assets/frontPage/card1.png
  public/assets/frontPage/card2.png
  public/assets/frontPage/card3.png
  public/assets/frontPage/card4.png
  src/components/frontPage/ConditionsSection.tsx
  src/pages/FrontPage.tsx
Labels: :sparkles: enhancement, frontend, form input, epic

#89 FEAT : FAQ Page
  public/assets/frontPage/bgFAQpage.png
  src/App.tsx
  src/components/homePage/FAQPageComponent.tsx
  src/pages/FAQPage.tsx
Labels: :sparkles: enhancement, frontend, form input

#91 Feat(parent data form)
  public/assets/regisPage/red_postit.svg
  src/components/Checkboxinput.tsx
  src/components/SelectInput.tsx
  src/components/Telephoneinputbox.tsx
  src/components/registrationForm/ParentDataForm.tsx
Labels: :sparkles: enhancement, form input, epic

#92 fix: center element in navbar
  src/components/registrationForm/Navbar.tsx
Labels: frontend, fix

#100 FEAT : Assemble all components in Registration page
  package-lock.json
  package.json
  public/assets/regisPage/trash.svg
  public/assets/regisPage/uploadFormBG.png
  public/assets/regisPage/yellow_postit.svg
  src/components/FileUploaderComponent.tsx
  src/components/GpaxInput.tsx
  src/components/Inputbox.tsx
  src/components/Textareainput.tsx
  src/components/registrationForm/ConsentForm.tsx
  src/components/registrationForm/EducationForm.tsx
  src/components/registrationForm/InterestForm.tsx
  src/components/registrationForm/ParentDataForm.tsx
  src/components/registrationForm/PersonalInfoForm.tsx
  src/components/registrationForm/QuestionFormpage1.tsx
  src/components/registrationForm/QuestionFormpage2.tsx
  src/components/registrationForm/UploadFilesForm.tsx
  src/index.css
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, form input, epic

#101 HOTFIX : Failed to load resource on server
  src/components/FileUploaderComponent.tsx
  src/components/registrationForm/UploadFilesForm.tsx
Labels: bug, frontend, fix

#107 FIX : Components on Registration page
  src/App.tsx
  src/components/DropdownSearch.tsx
  src/components/EmailInput.tsx
  src/components/GpaxInput.tsx
  src/components/Inputbox.tsx
  src/components/SelectInput.tsx
  src/components/Telephoneinputbox.tsx
  src/components/Textareainput.tsx
  src/components/registrationForm/InterestForm.tsx
  src/components/registrationForm/PersonalInfoForm.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, form input, epic

#109 REFACTOR & FEAT : Validator input & Change some selector input to dropdownsearch
  src/components/Checkboxinput.tsx
  src/components/DropdownSearch.tsx
  src/components/EmailInput.tsx
  src/components/FileUploaderComponent.tsx
  src/components/GpaxInput.tsx
  src/components/Inputbox.tsx
  src/components/SelectInput.tsx
  src/components/Telephoneinputbox.tsx
  src/components/Textareainput.tsx
  src/components/registrationForm/DropdownData/course_name.json
  src/components/registrationForm/EducationForm.tsx
  src/components/registrationForm/InterestForm.tsx
  src/components/registrationForm/ParentDataForm.tsx
  src/components/registrationForm/PersonalInfoForm.tsx
  src/components/registrationForm/QuestionFormpage1.tsx
  src/components/registrationForm/QuestionFormpage2.tsx
  src/components/registrationForm/UploadFilesForm.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, form input, epic, fix

#112 fix: overlapsed navbar
  src/pages/FrontPage.tsx
Labels: frontend, epic, fix

#113 chore: relocate component and page
  src/components/homePage/LandingSection.tsx
  src/components/homePage/Navbar.tsx
  src/pages/FAQPage.tsx
  src/pages/FrontPage.tsx
Labels: frontend, chores

#114 fix: slower parallax on mobile
  src/components/homePage/LandingSection.tsx
Labels: frontend, fix

#116 fix: navbar issues on ipad
  src/components/homePage/Navbar.tsx
Labels: frontend, fix

#120 ✨feat: Google Login
  public/assets/large-logo.png
  public/assets/nav-logo.png
  public/assets/regisPage/bgLogin.png
  src/App.tsx
  src/components/homePage/LandingSection.tsx
  src/components/homePage/Navbar.tsx
  src/pages/LoginPage.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, frontend, epic, backend

#121 feat: mockup section
  public/assets/frontPage/bgSponsorSectionDesktop.png
  public/assets/frontPage/bgSponsorSectionMobile.png
  src/components/homePage/SponsorSection.tsx
  src/pages/FrontPage.tsx
Labels: frontend, epic

#125 :adhesive_bandage:FIX : Registration page Inputbox & combine Date of birth before send POST method to our API
  src/components/DropdownSearch.tsx
  src/components/registrationForm/DropdownData/month_data.json
  src/components/registrationForm/PersonalInfoForm.tsx
  src/pages/RegistrationPage.tsx
Labels: backend, fix

#130 FEAT : Navbar scrolling & Scroll to top Button
  package-lock.json
  package.json
  src/components/homePage/AboutSection.tsx
  src/components/homePage/ConditionsSection.tsx
  src/components/homePage/ContactSection.tsx
  src/components/homePage/FAQSection.tsx
  src/components/homePage/Footer.tsx
  src/components/homePage/LearningSection.tsx
  src/components/homePage/Navbar.tsx
  src/components/homePage/SponsorSection.tsx
  src/components/homePage/TimelineSection.tsx
  src/pages/FrontPage.tsx
Labels: frontend

#138 :adhesive_bandage:FIX : padding heading text
  src/components/homePage/AboutSection.tsx
  src/components/homePage/ConditionsSection.tsx
  src/components/homePage/FAQSection.tsx
  src/components/homePage/LearningSection.tsx
  src/components/homePage/Navbar.tsx
  src/components/homePage/TimelineSection.tsx
Labels: :sparkles: enhancement, frontend, fix

#145 Co-authored-by: SSSBoOm <boom1909chanapat@gmail.com>
  src/components/FileUploaderComponent.tsx
  src/components/registrationForm/UploadFilesForm.tsx
  src/pages/RegistrationPage.tsx
Labels: :sparkles: enhancement, form input, backend, fix

#149 🚑 HOTFIX : Landing page
  src/App.tsx
  src/components/ScrollTotop.tsx
  src/components/homePage/AboutSection.tsx
  src/components/homePage/ConditionsSection.tsx
  src/components/homePage/ContactSection.tsx
  src/components/homePage/FAQSection.tsx
  src/components/homePage/Footer.tsx
  src/components/homePage/LandingSection.tsx
  src/components/homePage/LearningSection.tsx
  src/components/homePage/Navbar.tsx
  src/components/homePage/TimelineSection.tsx
Labels: :sparkles: enhancement, frontend, epic, fix

#150 :adhesive_bandage:FIX : Styling & Wording
  src/components/FileUploaderComponent.tsx
  src/components/Inputbox.tsx
  src/components/registrationForm/ConsentForm.tsx
  src/components/registrationForm/EducationForm.tsx
  src/components/registrationForm/InterestForm.tsx
  src/components/registrationForm/ParentDataForm.tsx
  src/components/registrationForm/PersonalInfoForm.tsx
  src/components/registrationForm/UploadFilesForm.tsx
Labels: :sparkles: enhancement, frontend, form input, epic, fix

#153 :adhesive_bandage:FIX : Upload & Download button
  src/components/FileUploaderComponent.tsx
Labels: :sparkles: enhancement, question, frontend, form input, epic, fix

#155 fix: scroll speed faster in About section
  src/components/homePage/AboutSection.tsx
Labels: :sparkles: enhancement, frontend, epic, fix

#161 :sparkles:ADD : Examination Info (page 2)
  src/components/ConfirmmationForm/ExaminationInfo.tsx
  src/lib/CustomSwal.ts
  src/pages/ResultPage.tsx
Labels: :sparkles: enhancement, frontend, epic
